[package]
name = "ident-str"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
macro-string = "0.1.4"
proc-macro2 = { version = "1.0.103", features = ["span-locations"] }
quote = "1.0.42"
syn = "2.0.110"
